import Mathlib

/-!
# Descent lemma and finite-index congruences

Two targets from "Congruence lattices of world models":

1. **Descent lemma** (§6): a surjective intertwiner `L : V' → V` between two
   observable-operator families forces a surjective monoid homomorphism
   `φ : S_agent →* S` between the generated transition monoids, with
   `φ (ρ' w) = ρ w`.

2. **`Con_f` is a filter** (§8 replacement for Remark 3): the finite-index
   congruences of a monoid form an up-set closed under finite meets.

Design notes:

* No linear algebra. The proof of descent uses only surjectivity of `L` and
  the pointwise intertwining relation, so everything is stated for bare
  functions on bare types. Linearity of `L` is a fact about where `L` comes
  from (sufficiency), not about descent.

* Composition convention: `FreeMonoid.lift T` sends `o₁ ⋯ oₙ` to
  `T o₁ ∘ ⋯ ∘ T oₙ`, the opposite of the paper's row-vector convention
  `T_{oₙ} ⋯ T_{o₁}`. The transition monoid here is therefore the opposite
  monoid of the paper's `S`. Since `Con S ≃ Con Sᵐᵒᵖ` canonically, every
  lattice-theoretic conclusion transfers verbatim.
-/

namespace Dovetail

variable {O V V' : Type*}

/-- The transition monoid generated by an observable-operator family:
the range of the induced representation `FreeMonoid O →* Function.End V`. -/
def transitionMonoid (T : O → Function.End V) : Submonoid (Function.End V) :=
  MonoidHom.mrange (FreeMonoid.lift T)

section Descent

variable (T : O → Function.End V) (T' : O → Function.End V') (L : V' → V)

/-- **Intertwining extension.** If `L` intertwines the generators, it
intertwines every word. Pure induction on word length; no surjectivity,
no linearity.

Proof plan: `induction w using FreeMonoid.recOn`; base case is `map_one`
plus `id`; inductive step is `map_mul` plus the generator hypothesis `h`.
Useful simp lemmas: `FreeMonoid.lift_eval_of`, `map_mul`, `map_one`,
`Function.End.mul_def` (or `End.mul_def` / unfold `(· * ·)` to `∘`). -/
theorem intertwine_extend
    (h : ∀ (o : O) (v' : V'), L (T' o v') = T o (L v')) :
    ∀ (w : FreeMonoid O) (v' : V'),
      L ((FreeMonoid.lift T') w v') = (FreeMonoid.lift T) w (L v') := by
  intro w
  induction w using FreeMonoid.recOn with
  | h0 =>
    intro v'
    simp [Function.End.one_def]
  | ih o w ihw =>
    intro v'
    simp only [map_mul, FreeMonoid.lift_eval_of, Function.End.mul_def,
      Function.comp_apply]
    rw [h, ihw]

/-- **Kernel inclusion.** If moreover `L` is surjective, words indistinguishable
to the agent are indistinguishable to the world:
`ker ρ' ≤ ker ρ` as congruences on the free monoid.

Proof plan: given `ρ' w = ρ' w'`, show `ρ w = ρ w'` by `funext v`; pick
`u` with `L u = v` via `hL`, then rewrite both sides through
`intertwine_extend`. `Con.ker_rel` unfolds the kernel congruence. -/
theorem ker_le_ker
    (hL : Function.Surjective L)
    (h : ∀ (o : O) (v' : V'), L (T' o v') = T o (L v')) :
    Con.ker (FreeMonoid.lift T') ≤ Con.ker (FreeMonoid.lift T) := by
  rw [Con.le_def]
  intro w w' hww'
  rw [Con.ker_rel] at hww' ⊢
  funext v
  obtain ⟨u, rfl⟩ := hL v
  rw [← intertwine_extend T T' L h, ← intertwine_extend T T' L h, hww']

/-- **Descent.** A surjective intertwiner induces a surjective monoid
homomorphism `S_agent →* S` sending `ρ' w` to `ρ w`.

Proof plan: `ker_le_ker` gives well-definedness. Route through the first
isomorphism theorem for monoids: `Con.quotientKerEquivRange` identifies
`S_agent` with the quotient by `Con.ker (lift T')`, then `Con.lift` factors
`lift T` through that quotient (using `ker_le_ker`), landing in `S` after
corestriction (`MonoidHom.mrangeRestrict`). Surjectivity: `φ` hits each
`ρ w`, which generate. -/
theorem descent
    (hL : Function.Surjective L)
    (h : ∀ (o : O) (v' : V'), L (T' o v') = T o (L v')) :
    ∃ φ : transitionMonoid T' →* transitionMonoid T,
      Function.Surjective φ ∧
        ∀ w : FreeMonoid O,
          (φ ⟨(FreeMonoid.lift T') w, ⟨w, rfl⟩⟩ : Function.End V) =
            (FreeMonoid.lift T) w := by
  classical
  unfold transitionMonoid
  -- Corestrict `lift T` to its range; the kernel is unchanged.
  have hker : Con.ker (FreeMonoid.lift T') ≤
      Con.ker (FreeMonoid.lift T).mrangeRestrict := by
    rw [Con.le_def]
    intro w w' hww'
    have hT := ker_le_ker T T' L hL h hww'
    rw [Con.ker_rel] at hT ⊢
    exact Subtype.ext hT
  set e := Con.quotientKerEquivRange (FreeMonoid.lift T') with he
  refine ⟨((Con.ker (FreeMonoid.lift T')).lift
      (FreeMonoid.lift T).mrangeRestrict hker).comp e.symm.toMonoidHom, ?_, ?_⟩
  · exact (Con.lift_surjective_of_surjective hker
      (FreeMonoid.lift T).mrangeRestrict_surjective).comp e.symm.surjective
  · intro w
    have hsymm : e.symm ⟨(FreeMonoid.lift T') w, ⟨w, rfl⟩⟩ =
        (w : (Con.ker (FreeMonoid.lift T')).Quotient) := by
      rw [MulEquiv.symm_apply_eq]
      exact Subtype.ext rfl
    simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, hsymm]
    rfl

/- Next target (inheritance theorem, §6): with `κ := Con.ker φ`,
`Con.correspondence κ : {d // κ ≤ d} ≃o Con κ.Quotient` plus the first
isomorphism theorem gives `Con S ≅ [κ, ⊤] ⊆ Con S_agent`, and hence
verbatim transport of every M₃/N₅. Stub it only after `descent` compiles. -/

end Descent

section FiniteIndex

variable {M : Type*} [Monoid M]

/-- A congruence has finite index if its quotient is finite. This is the
agent-accessible part of the description hierarchy: a finite-memory agent
implements only coarse-grainings with finitely many blocks. No finiteness
of `M` is assumed. -/
def _root_.Con.FiniteIndex (c : Con M) : Prop :=
  Finite c.Quotient

/-- `Con_f` is an up-set: coarsenings of finite-index congruences have
finite index.

Proof plan: `c ≤ d` induces a surjection `c.Quotient → d.Quotient`
(`Quotient.map id` with the compatibility from `h`, or `Con.map`);
conclude with `Finite.of_surjective`. -/
theorem _root_.Con.FiniteIndex.of_le {c d : Con M} (h : c ≤ d)
    (hc : c.FiniteIndex) : d.FiniteIndex := by
  have : Finite c.Quotient := hc
  exact Finite.of_surjective (c.map d h) fun x =>
    Con.induction_on x fun y => ⟨(y : c.Quotient), rfl⟩

/-- `Con_f` is closed under binary meets: blocks of `c ⊓ d` are
intersections of blocks.

Proof plan: `fun x => (⟦x⟧, ⟦x⟧)` descends to an injection
`(c ⊓ d).Quotient → c.Quotient × d.Quotient`; conclude with
`Finite.of_injective`. -/
theorem _root_.Con.FiniteIndex.inf {c d : Con M}
    (hc : c.FiniteIndex) (hd : d.FiniteIndex) : (c ⊓ d).FiniteIndex := by
  have : Finite c.Quotient := hc
  have : Finite d.Quotient := hd
  refine Finite.of_injective
    (fun x : (c ⊓ d).Quotient =>
      (((c ⊓ d).map c inf_le_left) x, ((c ⊓ d).map d inf_le_right) x))
    fun x y hxy => ?_
  induction x, y using Con.induction_on₂ with
  | _ a b =>
    obtain ⟨hcab, hdab⟩ := Prod.mk.injEq .. ▸ hxy
    exact (c ⊓ d).eq.2 (Con.inf_iff_and.2 ⟨c.eq.1 hcab, d.eq.1 hdab⟩)

/- Together: `Con_f` is a filter of `Con M`, hence a sublattice; it contains
`⊤` always and `⊥` iff `M` is finite. The index-exact restriction of the
inheritance theorem (`Con_f S ≅ [κ,⊤] ∩ Con_f S_agent`) belongs after the
descent chain compiles. -/

end FiniteIndex

#print axioms descent
#print axioms intertwine_extend
#print axioms ker_le_ker
#print axioms Con.FiniteIndex.of_le
#print axioms Con.FiniteIndex.inf

end Dovetail
